CXREF
      SUBROUTINE YLM(XLAT,XLON,LMAX,YLEN,WKLEN,Y,WK1,WK2,WK3)
C
Cf2py intent(inout) XLAT,XLON,LMAX,WKLEN,YLEN
Cf2py intent(out) Y,WK1,WK2,WK3
Cf2py depend(WKLEN) WK1,WK2,WK3
Cf2py depend(YLEN) Y
      IMPLICIT NONE
      COMPLEX TEMP,FAC,DFAC
      INTEGER LMAX,YLEN,WKLEN
      REAL*8 XLAT,XLON
c     dimension was not working with f2py
      REAL*8 WK1(WKLEN)
      REAL*8 WK2(WKLEN)
      REAL*8 WK3(WKLEN)
      REAL*8 Y(YLEN)
      
      REAL*8 THETA,PHI,RADIAN
      INTEGER IL1,L,IND,IM,LM1
C
C     WK1,WK2,WK3 SHOULD BE DIMENSIONED AT LEAST (LMAX+1)*4
C
      DATA RADIAN/57.2957795/
C
      THETA=(90.d0-XLAT)/RADIAN
      PHI=XLON/RADIAN
C
      IND=0
      LM1=LMAX+1
      DO 10 IL1=1,LM1
      L=IL1-1
      CALL LEGNDR(THETA,L,L,WKLEN,WK1,WK2,WK3)
C
      FAC=(1.,0.)
      DFAC=CEXP(CMPLX(0.,PHI))
C
      DO 20 IM=1,IL1
      TEMP=FAC*CMPLX(WK1(IM),0.)
      IND=IND+1
      Y(IND)=REAL(TEMP)
      IF(IM.EQ.1) GOTO 20
      IND=IND+1
      Y(IND)=AIMAG(TEMP)
   20 FAC=FAC*DFAC
C
   10 CONTINUE
      RETURN
      END
