.. _changes_0_1_0:

Version 0.1.0 (2023-10-22)
--------------------------

- Initial release (initial commit: 2017-06-28).
- This version contains basic API codebase with functionalities
  to query locally hosted models and data. Some public (non-authenticated)
  queries from the AVNI server have also been implemented.
- Model and Surface Wave Reference Data Formats (RSDF) in
  both ASCII and HDF5 formats have been updated.

Authors
~~~~~~~

The core committer list for this release is the following:

* :newcontrib:`Raj Moulik`
* :newcontrib:`Ross Maguire`
* :newcontrib:`Rene Gassmoeller`
* :newcontrib:`Chris Havlin`
