# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/romaguir/rem3d/rem3d/slicer_gui/layout.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1074, 795)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lat_min_slider = QtGui.QSlider(self.centralwidget)
        self.lat_min_slider.setMinimum(-90)
        self.lat_min_slider.setMaximum(90)
        self.lat_min_slider.setProperty("value", -90)
        self.lat_min_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lat_min_slider.setObjectName(_fromUtf8("lat_min_slider"))
        self.gridLayout_3.addWidget(self.lat_min_slider, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 6, 0, 1, 1)
        self.lon_max_slider = QtGui.QSlider(self.centralwidget)
        self.lon_max_slider.setMinimum(-180)
        self.lon_max_slider.setMaximum(180)
        self.lon_max_slider.setProperty("value", 180)
        self.lon_max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lon_max_slider.setObjectName(_fromUtf8("lon_max_slider"))
        self.gridLayout_3.addWidget(self.lon_max_slider, 6, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 5, 1, 1, 1)
        self.lon_min_slider = QtGui.QSlider(self.centralwidget)
        self.lon_min_slider.setMinimum(-180)
        self.lon_min_slider.setMaximum(180)
        self.lon_min_slider.setProperty("value", -180)
        self.lon_min_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lon_min_slider.setObjectName(_fromUtf8("lon_min_slider"))
        self.gridLayout_3.addWidget(self.lon_min_slider, 4, 1, 1, 1)
        self.lat_max_slider = QtGui.QSlider(self.centralwidget)
        self.lat_max_slider.setMinimum(-90)
        self.lat_max_slider.setMaximum(90)
        self.lat_max_slider.setProperty("value", 90)
        self.lat_max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.lat_max_slider.setObjectName(_fromUtf8("lat_max_slider"))
        self.gridLayout_3.addWidget(self.lat_max_slider, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 7, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 6, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Vp_button = QtGui.QPushButton(self.centralwidget)
        self.Vp_button.setObjectName(_fromUtf8("Vp_button"))
        self.horizontalLayout_2.addWidget(self.Vp_button)
        self.Vs_button = QtGui.QPushButton(self.centralwidget)
        self.Vs_button.setObjectName(_fromUtf8("Vs_button"))
        self.horizontalLayout_2.addWidget(self.Vs_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 5, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 8, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.hotspots_box = QtGui.QCheckBox(self.centralwidget)
        self.hotspots_box.setObjectName(_fromUtf8("hotspots_box"))
        self.gridLayout_4.addWidget(self.hotspots_box, 0, 2, 1, 1)
        self.coastlines_box = QtGui.QCheckBox(self.centralwidget)
        self.coastlines_box.setChecked(True)
        self.coastlines_box.setTristate(False)
        self.coastlines_box.setObjectName(_fromUtf8("coastlines_box"))
        self.gridLayout_4.addWidget(self.coastlines_box, 0, 0, 1, 1)
        self.cbar_max = QtGui.QDoubleSpinBox(self.centralwidget)
        self.cbar_max.setMaximum(10.0)
        self.cbar_max.setSingleStep(0.5)
        self.cbar_max.setProperty("value", 2.0)
        self.cbar_max.setObjectName(_fromUtf8("cbar_max"))
        self.gridLayout_4.addWidget(self.cbar_max, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.plate_boundaries_box = QtGui.QCheckBox(self.centralwidget)
        self.plate_boundaries_box.setObjectName(_fromUtf8("plate_boundaries_box"))
        self.gridLayout_4.addWidget(self.plate_boundaries_box, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 7, 0, 1, 1)
        self.depth_slider = QtGui.QSlider(self.centralwidget)
        self.depth_slider.setMinimum(25)
        self.depth_slider.setMaximum(2891)
        self.depth_slider.setSingleStep(5)
        self.depth_slider.setProperty("value", 25)
        self.depth_slider.setOrientation(QtCore.Qt.Horizontal)
        self.depth_slider.setObjectName(_fromUtf8("depth_slider"))
        self.gridLayout_2.addWidget(self.depth_slider, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBox = QtGui.QComboBox(self.centralwidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox)
        self.global_map = Qt4MplCanvas(self.centralwidget)
        self.global_map.setObjectName(_fromUtf8("global_map"))
        self.verticalLayout_2.addWidget(self.global_map)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.submit_button = QtGui.QPushButton(self.centralwidget)
        self.submit_button.setObjectName(_fromUtf8("submit_button"))
        self.horizontalLayout_5.addWidget(self.submit_button)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(2, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.local_map = Qt4MplCanvas(self.centralwidget)
        self.local_map.setObjectName(_fromUtf8("local_map"))
        self.verticalLayout_3.addWidget(self.local_map)
        self.cross_section_button = QtGui.QPushButton(self.centralwidget)
        self.cross_section_button.setObjectName(_fromUtf8("cross_section_button"))
        self.verticalLayout_3.addWidget(self.cross_section_button)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.cross_section = Qt4MplCanvas(self.centralwidget)
        self.cross_section.setObjectName(_fromUtf8("cross_section"))
        self.verticalLayout_4.addWidget(self.cross_section)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1074, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_6.setText(_translate("MainWindow", "lon max", None))
        self.label_5.setText(_translate("MainWindow", "lon min", None))
        self.label_4.setText(_translate("MainWindow", "lat max", None))
        self.label_3.setText(_translate("MainWindow", "lat min", None))
        self.Vp_button.setText(_translate("MainWindow", "Vp", None))
        self.Vs_button.setText(_translate("MainWindow", "Vs", None))
        self.hotspots_box.setText(_translate("MainWindow", "hotspots", None))
        self.coastlines_box.setText(_translate("MainWindow", "coastlines", None))
        self.label_7.setText(_translate("MainWindow", "colorbar max (%)", None))
        self.plate_boundaries_box.setText(_translate("MainWindow", "plate boundaries", None))
        self.label_2.setText(_translate("MainWindow", "parameter", None))
        self.label.setText(_translate("MainWindow", "depth (km)", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "S362ANI+M (Moulik and Ekstrom, 2014)", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "S40RTS", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "GAP_P4", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "MITP08", None))
        self.submit_button.setText(_translate("MainWindow", "submit", None))
        self.cross_section_button.setText(_translate("MainWindow", "calculate cross section", None))

from instaseis.gui.qt4mplcanvas import Qt4MplCanvas
