.. buttons
.. |home| image:: https://img.shields.io/badge/AVNI-Website-green?logo=googlehome&logoColor=white
   :target: `AVNI`_
.. |REM3D| image:: https://img.shields.io/badge/REM3D-Website-blue?logo=googlehome&logoColor=white
   :target: `REM3D`_
.. |Github| image:: https://img.shields.io/badge/AVNI-GitHub-blue?logo=github
   :target: `AVNI GitHub`_
.. |pypi_button| image:: https://img.shields.io/pypi/v/avni?logo=python&logoColor=white
   :target: `PyPI`_
.. |GNU GPL| image:: https://img.shields.io/badge/License-GNU%20GPL%20v3-orange?logo=gnu
   :target: `LICENSE`_
.. |issues| image:: https://img.shields.io/badge/GitHub-Issues-green?logo=github
   :target: `GitHub issues page`_
.. |python_button| image:: https://img.shields.io/badge/python-3.6+-blue.svg
   :target: https://www.python.org/downloads/
.. |discuss| image:: https://img.shields.io/badge/GitHub-Discussions-blue?logo=github
   :target: `AVNI Forum`_
.. |tweet| image:: https://img.shields.io/twitter/url.svg?style=social&url=http%3A%2F%2Fshields.io
   :target: https://twitter.com/intent/tweet?text=Check%20out%20this%20project%20for%20Earth%20and%20other%20planets%20in%20Python&url=https://avni.globalseismology.org&hashtags=3D,visualization,Python,vtk,mesh,plotting,AVNI
.. |Hubzero| image:: https://img.shields.io/badge/Launch-Hubzero-yellow?logo=hotelsdotcom&logoColor=white
   :target: `AVNI Hubzero`_
   :alt: Launch on Hubzero
