# -*- coding: utf-8 -*-
#
# AVNI documentation build configuration file, created by
# sphinx-quickstart on Wed Apr 26 2019.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import shlex
import sphinx_fontawesome

from datetime import datetime, timezone
from dateutil import tz
import faulthandler
import locale
import sphinx

# Otherwise VTK reader issues on some systems, causing sphinx to crash. See also #226.
locale.setlocale(locale.LC_ALL, "en_US.UTF-8")

faulthandler.enable()

# -- Path setup --------------------------------------------------------------
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
curdir = os.path.dirname(__file__)
sys.path.append(os.path.abspath(os.path.join(curdir, '..', 'avni')))
sys.path.append(os.path.abspath(os.path.join(curdir, 'sphinxext')))

# avoid gfortran not being available on readthedocs
# https://read-the-docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
# if (sys.version_info[:2] < (3, 3)):
#     from mock import Mock as MagicMock
# else:
#     from unittest.mock import MagicMock
#
# class Mock(MagicMock):
#     @classmethod
#     def __getattr__(cls, name):
#         return MagicMock()
#
# MOCK_MODULES = ['avni']
# sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)

#import avni


# -- Project information -----------------------------------------------------

# In order for the Sphinx MATLAB domain to auto-document MATLAB source code,
# set the config value of matlab_src_dir to the absolute path instead of adding
# them to sys.path. Currently only one MATLAB path can be specified, but all
# subfolders in that tree will be searched.
#matlab_src_dir = '../avni-matlab'

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "myst_parser",
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'numpydoc',
    'sphinx.ext.ifconfig',
    'sphinx.ext.inheritance_diagram',
    'sphinx.ext.viewcode',
    'sphinxcontrib.bibtex',
    'sphinx_gallery.gen_gallery',
    'sphinx_fontawesome',
    'jupyter_sphinx',
    'sphinx_design',
    'sphinxcontrib.youtube',
    'gh_substitutions',
    'newcontrib_substitutions',
    'gen_names'
]

#    'sphinxcontrib.matlab',

myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "fieldlist",
    "substitution",
    "dollarmath",
    "amsmath",
]

# --------------------------------
# Sphinx Gallery config
sphinx_gallery_conf = {
    # path to your example scripts
    #'examples_dirs': ['../examples/Notebooks'],
    # path to where to save gallery generated output
    'gallery_dirs': ["tutorials"],
    # Checks matplotlib for figure creation
    'image_scrapers': ('matplotlib'),
    # Which files to include
    'filename_pattern': r"\.py"
}


# sphinxcontrib-bibtex
bibtex_bibfiles = ['./references.bib']
bibtex_style = 'unsrt'
bibtex_footbibliography_header = ''


numpydoc_show_class_members = False

# autodoc / autosummary
autosummary_generate = True
autodoc_default_options = {'inherited-members': None}

autodoc_default_flags = [
    'members', 'undoc-members', 'show-inheritance', 'inherited-members']
autodoc_member_order = 'bysource'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# Add the Markdown parser to the source_parsers configuration
# variable in your Sphinx configuration file:
# http://www.sphinx-doc.org/en/stable/markdown.html
source_parsers = {
   '.md': 'recommonmark.parser.CommonMarkParser',
}

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = ['.rst', '.md']

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'


# -- Project information -----------------------------------------------------

project = u'AVNI'
td = datetime.now(tz=timezone.utc)
to_zone = tz.tzlocal()

# We need to triage which date type we use so that incremental builds work
# (Sphinx looks at variable changes and rewrites all files if some change)
copyright = (
    f'2016–{td.year}, AVNI Developers. Last updated {td.astimezone(to_zone).strftime("%b %d, %Y, %I:%M:%S %p %Z")}')
author = u'Pritwiraj (Raj) Moulik'


# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
#version = '0.1.0'
#version = avni.version.short_version
exec(open("../avni/version.py").read())
version = short_version

# The full version, including alpha/beta/rc tags.
#release = '0.1.0'
#release = avni.__version__
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'api/avni.rst','api/avni.version.rst']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#html_theme = 'alabaster'
#html_theme = "sphinx_rtd_theme"
html_theme = "pydata_sphinx_theme"
#html_theme = "sphinx_book_theme"

# Define the json_url for our version switcher.
json_url = "https://portal.globalseismology.org/docs/avni/dev/_static/versions.json"
switcher_version_match = 'dev' if release.endswith('dev0') else version


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
     "navbar_align": "left",  # [left, content, right] For testing that the navbar items align properly
    "show_prev_next": True,
    "collapse_navigation": True,
    "analytics": dict(google_analytics_id='G-WB7DQMP0XP'),
    "icon_links": [
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/avni",
            "icon": "fa-solid fa-box",
        },
        {
            "name": "Support",
            "url": "https://github.com/globalseismology/avni/discussions",
            "icon": "fa fa-comment fa-fw",
        },
        {
            "name": "Website",
            "url": "https://avni.globalseismology.org",
            "icon": "_static/logo_avni_bw.png",
            "type": "local",
            "attributes": {"target": "_blank"},
        },
    ],
    'icon_links_label': 'External Links',  # for screen reader
    "external_links": [
        {
            "url": "https://dwar.princeton.edu:8443/realms/GlobalSeismology/protocol/openid-connect/auth?client_id=web_js&response_type=code&scope=openid&redirect_uri=https%3A//portal.globalseismology.org/docs/avni",
            "name": "Register",
        },
    ],
    "github_url": "https://github.com/globalseismology/avni",
    'use_edit_page_button': False,
    'navigation_with_keys': False,
    'show_toc_level': 1,
    'navbar_end': ['theme-switcher', 'version-switcher', 'navbar-icon-links'],
    'footer_items': ['copyright'],
    'secondary_sidebar_items': ['page-toc'],
    #'analytics': dict(google_analytics_id='G-5TBCPCRB6X'),
    'pygment_light_style': 'default',
    'pygment_dark_style': 'monokai',
    # "navbar_center": ["version-switcher", "navbar-nav"],
    # "show_nav_level": 2,
    # "navbar_start": ["navbar-logo"],
    # "navbar_persistent": ["search-button"],
    # "primary_sidebar_end": ["custom-template.html", "sidebar-ethical-ads.html"],
    #"secondary_sidebar_items": ["page-toc", "edit-this-page", "sourcelink"],
    "switcher": {
        "json_url": json_url,
        "version_match": switcher_version_match,
    }
    # "search_bar_position": "navbar",  # TODO: Deprecated - remove in future version

}

# accommodate different logo shapes (width values in rem)
xs = '2'
sm = '2.5'
md = '3'
lg = '4.5'
xl = '5'
xxl = '6'
# variables to pass to HTML templating engine
html_context = {
    "github_user": "globalseismology",
    "github_repo": "avni",
    "github_version": "main",
    "doc_path": "docs",
    # \u00AD is an optional hyphen (not rendered unless needed)
    # If these are changed, the Makefile should be updated, too
    'carousel': [
        dict(title='Data',
             text='Reconciliation of measurements and their predictions.',  # noqa E501
             url='auto_tutorials/stats-source-space/index.html',
             img='example_data.png',
             alt='Data'),
        dict(title='Models',
             text='Exploring and evaluating complex model descriptions.',  # noqa E501
             url='auto_tutorials/inverse_label_connectivity.html',  # noqa E501
             img='example_model.png',  # noqa E501
             alt='Models'),
        dict(title='Inferences',
             text='Making thermo-chemical and other inferences.',
             url='auto_tutorials/evoked/20_visualize_evoked.html',
             img='example_inference.png',
             alt='Inferences'),
    ]
}


# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "_static/logos/logo_avni_color_withname.svg"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "_static/logos/logo_avni_bw.png"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = [
    'style.css',
]

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
html_sidebars = {
    'index': ['sidebar-quicklinks.html'],
}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'AVNIdoc'

# -- Options for plot_directive ----------------------------------------------

# Adapted from SciPy
plot_include_source = True
plot_formats = [('png', 96)]
plot_html_show_formats = False
plot_html_show_source_link = False
font_size = 13 * 72 / 96.0  # 13 px
plot_rcparams = {
    'font.size': font_size,
    'axes.titlesize': font_size,
    'axes.labelsize': font_size,
    'xtick.labelsize': font_size,
    'ytick.labelsize': font_size,
    'legend.fontsize': font_size,
    'figure.figsize': (6, 5),
    'figure.subplot.bottom': 0.2,
    'figure.subplot.left': 0.2,
    'figure.subplot.right': 0.9,
    'figure.subplot.top': 0.85,
    'figure.subplot.wspace': 0.4,
    'text.usetex': False,
}

# -- Fontawesome support -----------------------------------------------------

brand_icons = ('apple', 'linux', 'windows', 'discourse', 'python')
fixed_width_icons = (
    # homepage:
    'book', 'code-branch', 'newspaper', 'circle-question', 'quote-left',
    # contrib guide:
    'bug-slash', 'comment', 'computer-mouse', 'hand-sparkles', 'pencil',
    'text-slash', 'universal-access', 'wand-magic-sparkles',
    'discourse', 'python',
)
other_icons = (
    'hand-paper', 'question', 'rocket', 'server', 'code', 'desktop',
    'terminal', 'cloud-arrow-down', 'wrench', 'hourglass-half'
)
icon_class = dict()
for icon in brand_icons + fixed_width_icons + other_icons:
    icon_class[icon] = ('fa-brands',) if icon in brand_icons else ('fa-solid',)
    icon_class[icon] += ('fa-fw',) if icon in fixed_width_icons else ()

prolog = ''
for icon, classes in icon_class.items():
    prolog += f'''
.. |{icon}| raw:: html

    <i class="{' '.join(classes + (f'fa-{icon}',))}"></i>
'''

prolog += '''
.. |ensp| unicode:: U+2002 .. EN SPACE
'''

# -- Dependency info ----------------------------------------------------------

try:
    from importlib.metadata import metadata  # new in Python 3.8
    min_py = metadata('avni')['Requires-Python']
except ModuleNotFoundError:
    from pkg_resources import get_distribution
    info = get_distribution('avni').get_metadata_lines('PKG-INFO')
    for line in info:
        if line.strip().startswith('Requires-Python'):
            min_py = line.split(':')[1]
min_py = min_py.lstrip(' =<>')
prolog += f'\n.. |min_python_version| replace:: {min_py}\n'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
'papersize': 'letterpaper',
'babel': r'\usepackage[english]{babel}',

# The font size ('10pt', '11pt' or '12pt').
'pointsize': '11pt',

# Additional stuff for the LaTeX preamble.
'preamble': r'''
\usepackage{lmodern}
\usepackage{subfigure}
\usepackage{textpos}
\usepackage{svg}

% This adds space between the Appendix number (e.g., A.101) and the title.
\renewcommand{\numberline}[1]{#1~}

% If your page numbers stick out into the right-hand margin but using lengths
% appropriate to your document. See the Introduction to the "The tocloft
% package" for additional information.
\makeatletter
 \renewcommand{\@pnumwidth}{1.75em}
 \renewcommand{\@tocrmarg}{3.25em}
\makeatother

% have an index. we use the imakeidx' replacement of the 'multind' package so
% that we can have an index of all run-time parameters separate from other
% items (if we ever wanted one)
\usepackage{imakeidx}
\makeindex[name=prmindex, title=Index of run-time parameter entries]
\makeindex[name=prmindexfull, title=Index of run-time parameters with section names]

\newcommand{\manual}{\textsc{Analysis and Visualization toolkit for plaNetary Inferences}}
    ''',

    'maketitle': r'''
\definecolor{dark_grey}{gray}{0.3}
\definecolor{aspect_blue}{rgb}{0.3125,0.6875,0.9375}

%LINE 1%
{
\renewcommand{\familydefault}{\sfdefault}

\pagenumbering{gobble}
\begin{center}
\resizebox{\textwidth}{!}{\textcolor{dark_grey}{\fontfamily{\sfdefault}\selectfont
COMPUTATIONAL INFRASTRUCTURE FOR GEODYNAMICS (CIG)
}}

\hrule

%LINE 2%
\color{dark_grey}
\rule{\textwidth}{2pt}

%LINE 3%
\color{dark_grey}
% FILL: additional organizations
% e.g.: {\Large Organization 1\\Organization 2}
{\Large }
\end{center}

%COLOR AND CODENAME BLOCK%
\begin{center}
\resizebox{\textwidth}{!}{\colorbox
% FILL: color of code name text box
% e.g. blue
{aspect_blue}{\fontfamily{\rmdefault}\selectfont \textcolor{white} {
% FILL: name of the code
% You may want to add \hspace to both sides of the codename to better center it, such as:
% \newcommand{\codename}{\hspace{0.1in}CodeName\hspace{0.1in}}
\hspace{0.1in}\manual{}\hspace{0.1in}} }}
\\[15pt]
{\Large Software User Manual}
\end{center}

%MAIN PICTURE%
\begin{textblock*}{0in}(1.5in,0.3in)
% FILL: image height
% e.g. height=6.5in
\begin{center}
\vspace{1em}
\includegraphics[height=3.5in]{logo_avni_color.png}
\hspace{5em}
\end{center}
\end{textblock*}

%USER MANUAL%
\color{dark_grey}
\hfill{\Huge \fontfamily{\sfdefault}\selectfont AVNI \\
\raggedleft \huge \fontfamily{\sfdefault}\selectfont Version
% keep the following line as is so that we can replace this using a script:
'''+
version+
r''' %VERSION-INFO%
\\\large(generated \today)\\
{\Large Pritwiraj (Raj) Moulik}
}

%AUTHOR(S) & WEBSITE%
\null
\vspace{17em}
\color{dark_grey}
{\fontfamily{\sfdefault}\selectfont
% FILL: author list
% e.g. Author One\\Author Two\\Author Three\\
% be sure to have a newline (\\) after the final author
\large
\vspace{3.0em}
\noindent with contributions by (in alphabetical order): \\
    Rene Gassmoeller,
    Chris Havlin,
    Ross Maguire\\
\vspace{1.0em}

{\noindent
{Website: \href{https://avni.globalseismology.org}{avni.globalseismology.org}}
}
}

\vspace{3.0em}


%LINE%
{\noindent
\color{dark_grey}
\rule{\textwidth}{2pt}
}

%COPYRIGHT STATEMENT
\textcopyright Copyright 2021, Pritwiraj (Raj) Moulik, AVNI Project and Regents of the University of California

}

\pagebreak
        '''

# Latex figure (float) alignment
#'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  (master_doc, 'manual_AVNI.tex', u'AVNI Documentation',
   u'Pritwiraj (Raj) Moulik', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = '_static/logos/logo_avni_color.png'

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'avni', u'AVNI Documentation',
     [author], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  (master_doc, 'AVNI', u'AVNI Documentation',
   author, 'AVNI', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The basename for the epub file. It defaults to the project name.
#epub_basename = project

# The HTML theme for the epub output. Since the default themes are not optimized
# for small screen space, using the same theme for HTML and epub output is
# usually not wise. This defaults to 'epub', a theme designed to save visual
# space.
#epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or 'en' if the language is not set.
#epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
#epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#epub_identifier = ''

# A unique identification for the text.
#epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
#epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_pre_files = []

# HTML files shat should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#epub_post_files = []

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# The depth of the table of contents in toc.ncx.
#epub_tocdepth = 3

# Allow duplicate toc entries.
#epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#epub_tocscope = 'default'

# Fix unsupported image types using the Pillow.
#epub_fix_images = False

# Scale large images.
#epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#epub_show_urls = 'inline'

# If false, no index is generated.
#epub_use_index = True


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}

# -- Connect our handlers to the main Sphinx app ---------------------------

def setup(app):
    """Set up the Sphinx app."""
    # A string of reStructuredText that will be included at the
    # beginning of every source file that is read.
    app.config.rst_prolog = prolog